name: Build and Deploy Docker
on:
  push:
    branches-ignore: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@master

    - name: Build Container
      run: docker build . -t ghcr.io/${{ github.repository }}:${{ github.sha }}

    - name: Scan container for issues
      uses: Azure/container-scan@v0.1
      with:
        image-name: ghcr.io/${{ github.repository }}:${{ github.sha }}
