name: Build Docker
on:
  push:
    branches-ignore: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master

    - name: Build Container
      run: docker build . -t ghcr.io/${{ github.repository }}:${{ github.sha }}

    - name: Scan container for issues
      uses: Azure/container-scan@f9af925b897d8af5f7e0026b8bca9346261abc93 # v0.1
      with:
        image-name: ghcr.io/${{ github.repository }}:${{ github.sha }}
